# Generated by Django 6.0.1 on 2026-02-03 05:03

from django.db import migrations, models


def backfill_positions(apps, schema_editor):
    """Backfill position field by ID order within each session."""
    Exercise = apps.get_model('lifting', 'Exercise')
    Session = apps.get_model('lifting', 'Session')

    for session in Session.objects.all():
        exercises = Exercise.objects.filter(session=session).order_by('id')
        for i, exercise in enumerate(exercises):
            exercise.position = i
            exercise.save(update_fields=['position'])


def reverse_backfill(apps, schema_editor):
    """Reverse migration - just set all positions to 0."""
    Exercise = apps.get_model('lifting', 'Exercise')
    Exercise.objects.all().update(position=0)


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0004_remove_old_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_positions, reverse_backfill),
    ]
