# Generated by Django 6.0.1 on 2026-10-04 22:57

from django.db import migrations, models


def mark_sets_done(apps, schema_editor):
    """Every set logged before the redesign was actually lifted."""
    Exercise = apps.get_model("lifting", "Exercise")
    for exercise in Exercise.objects.all():
        exercise.sets = [{**s, "done": True} for s in exercise.sets]
        exercise.save(update_fields=["sets"])


def unmark_sets_done(apps, schema_editor):
    Exercise = apps.get_model("lifting", "Exercise")
    for exercise in Exercise.objects.all():
        exercise.sets = [{k: v for k, v in s.items() if k != "done"} for s in exercise.sets]
        exercise.save(update_fields=["sets"])


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0005_add_exercise_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date', '-id']},
        ),
        # A default lets the removal be reversed.
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(default='volume', max_length=50),
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_type',
        ),
        migrations.AddField(
            model_name='exercise',
            name='superset_group',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('done', 'Done')], default='done', max_length=10),
        ),
        migrations.RunPython(mark_sets_done, unmark_sets_done),
    ]
